const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const html = fs.readFileSync(path.join(__dirname, '../static/index.html'), 'utf8');
const js = fs.readFileSync(path.join(__dirname, '../static/js/app.js'), 'utf8');
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
assert.equal(new Set(ids).size, ids.length, 'duplicate HTML IDs');
for (const [, id] of js.matchAll(/\$\('([^']+)'\)/g)) assert.ok(ids.includes(id), `missing element: ${id}`);
const toggle = html.match(/<input\b[^>]*id="speakerHlsEnabled"[^>]*>/)[0];
assert.ok(!/\bchecked\b/.test(toggle), 'HLS must default off');
assert.ok(html.indexOf('id="closeHlsSession"') < html.indexOf('id="playerDetail"'), 'cleanup must remain available with no book selected');
assert.ok(js.includes("speakerHlsEnabled: $('speakerHlsEnabled').checked"));
assert.match(html, /id="speakerHlsStartMode"><option value="selected">/);
assert.equal((js.match(/speakerHlsStartMode: \$\('speakerHlsStartMode'\).value/g) || []).length, 3);
assert.equal((js.match(/speakerHlsHostUrl: \$\('speakerHlsHostUrl'\).value/g) || []).length, 3);
assert.ok(js.includes('...result.history'), 'use actual stream position for history');
const plugin = JSON.parse(fs.readFileSync(path.join(__dirname, '../plugin.json'), 'utf8'));
assert.deepEqual(plugin.publicPaths, ['/speaker-stream/']);
console.log('UI IDs, default toggle and cleanup visibility checks passed.');
